name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint || true

      - name: Run Tests
        run: npm run test

      - name: Build Project
        run: npm run build

      # - name: Deploy to Server via SSH
      #   if: github.ref == 'refs/heads/main'
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     port: ${{ secrets.SERVER_PORT }}
      #     script: |
      #       cd ${{ secrets.SERVER_APP_PATH }}
      #       git pull origin main
      #       npm ci
      #       npm run build
      #       pm2 restart all